=== BernhardPosselt/foundryvtt-kotlin/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "skillRequirements",
        "skills",
        "isSecret",
        "isLocked"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skillRequirements": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillRequirement"
          }
        },
        "dc": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "zone",
                "actorLevel"
              ]
            }
          ]
        },
        "skills": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string",
              "enum": [
                "any"
              ]
            }
          ]
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        }
      }
    },
    "SkillRequirement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "skill",
        "proficiency"
      ],
      "properties": {
        "skill": {
          "type": "string"
        },
        "proficiency": {
          "type": "string"
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Regongar.json
{
    "name": "Discover Regongar",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Regongar has the lowest DC (skipping any skills that you already know), one of Regongar’s personal biases, one of Regongar’s resistances, or one of Regongar’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Regongar has the lowest DC (skipping any skills that you already know), one of Regongar’s personal biases, one of Regongar’s resistances, or one of Regongar’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Regongar is susceptible to flattery when actually Regongar is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Harrim.json
{
    "name": "Discover Harrim",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Harrim has the lowest DC (skipping any skills that you already know), one of Harrim’s personal biases, one of Harrim’s resistances, or one of Harrim’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Harrim has the lowest DC (skipping any skills that you already know), one of Harrim’s personal biases, one of Harrim’s resistances, or one of Harrim’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Harrim is susceptible to flattery when actually Harrim is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Jaethal.json
{
    "name": "Influence Jaethal",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Jaethal"
    },
    "success": {
        "message": "You gain 1 Influence Points with Jaethal"
    },
    "failure": {
        "message": "You gain no Influence Points with Jaethal"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Jaethal"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Jubilost.json
{
    "name": "Discover Jubilost",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Jubilost has the lowest DC (skipping any skills that you already know), one of Jubilost’s personal biases, one of Jubilost’s resistances, or one of Jubilost’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Jubilost has the lowest DC (skipping any skills that you already know), one of Jubilost’s personal biases, one of Jubilost’s resistances, or one of Jubilost’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Jubilost is susceptible to flattery when actually Jubilost is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Jaethal.json
{
    "name": "Discover Jaethal",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Jaethal has the lowest DC (skipping any skills that you already know), one of Jaethal’s personal biases, one of Jaethal’s resistances, or one of Jaethal’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Jaethal has the lowest DC (skipping any skills that you already know), one of Jaethal’s personal biases, one of Jaethal’s resistances, or one of Jaethal’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Jaethal is susceptible to flattery when actually Jaethal is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Linzi.json
{
    "name": "Discover Linzi",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Linzi has the lowest DC (skipping any skills that you already know), one of Linzi’s personal biases, one of Linzi’s resistances, or one of Linzi’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Linzi has the lowest DC (skipping any skills that you already know), one of Linzi’s personal biases, one of Linzi’s resistances, or one of Linzi’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Linzi is susceptible to flattery when actually Linzi is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Valerie.json
{
    "name": "Discover Valerie",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Valerie has the lowest DC (skipping any skills that you already know), one of Valerie’s personal biases, one of Valerie’s resistances, or one of Valerie’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Valerie has the lowest DC (skipping any skills that you already know), one of Valerie’s personal biases, one of Valerie’s resistances, or one of Valerie’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Valerie is susceptible to flattery when actually Valerie is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Tristian.json
{
    "name": "Discover Tristian",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Tristian has the lowest DC (skipping any skills that you already know), one of Tristian’s personal biases, one of Tristian’s resistances, or one of Tristian’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Tristian has the lowest DC (skipping any skills that you already know), one of Tristian’s personal biases, one of Tristian’s resistances, or one of Tristian’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Tristian is susceptible to flattery when actually Tristian is resistant to flattery."
    }
}
