=== BernhardPosselt/foundryvtt-kotlin/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "skillRequirements",
        "skills",
        "isSecret",
        "isLocked"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skillRequirements": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillRequirement"
          }
        },
        "dc": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "zone",
                "actorLevel"
              ]
            }
          ]
        },
        "skills": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string",
              "enum": [
                "any"
              ]
            }
          ]
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        }
      }
    },
    "SkillRequirement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "skill",
        "proficiency"
      ],
      "properties": {
        "skill": {
          "type": "string"
        },
        "proficiency": {
          "type": "string"
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Amiri.json
{
    "name": "Influence Amiri",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Amiri"
    },
    "success": {
        "message": "You gain 1 Influence Points with Amiri"
    },
    "failure": {
        "message": "You gain no Influence Points with Amiri"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Amiri"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Jubilost.json
{
    "name": "Influence Jubilost",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Jubilost"
    },
    "success": {
        "message": "You gain 1 Influence Points with Jubilost"
    },
    "failure": {
        "message": "You gain no Influence Points with Jubilost"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Jubilost"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Regongar.json
{
    "name": "Influence Regongar",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Regongar"
    },
    "success": {
        "message": "You gain 1 Influence Points with Regongar"
    },
    "failure": {
        "message": "You gain no Influence Points with Regongar"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Regongar"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Ekundayo.json
{
    "name": "Influence Ekundayo",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Ekundayo"
    },
    "success": {
        "message": "You gain 1 Influence Points with Ekundayo"
    },
    "failure": {
        "message": "You gain no Influence Points with Ekundayo"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Ekundayo"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Kalikke.json
{
    "name": "Discover Kalikke",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Kalikke has the lowest DC (skipping any skills that you already know), one of Kalikke’s personal biases, one of Kalikke’s resistances, or one of Kalikke’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Kalikke has the lowest DC (skipping any skills that you already know), one of Kalikke’s personal biases, one of Kalikke’s resistances, or one of Kalikke’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Kalikke is susceptible to flattery when actually Kalikke is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Amiri.json
{
    "name": "Discover Amiri",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Amiri has the lowest DC (skipping any skills that you already know), one of Amiri’s personal biases, one of Amiri’s resistances, or one of Amiri’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Amiri has the lowest DC (skipping any skills that you already know), one of Amiri’s personal biases, one of Amiri’s resistances, or one of Amiri’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Amiri is susceptible to flattery when actually Amiri is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Octavia.json
{
    "name": "Influence Octavia",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Octavia"
    },
    "success": {
        "message": "You gain 1 Influence Points with Octavia"
    },
    "failure": {
        "message": "You gain no Influence Points with Octavia"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Octavia"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Bolster Confidence.json
{
    "name": "Bolster Confidence",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.pxHYFLK7VYGppCzS",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": [],
    "effectUuids": [
        {
            "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.mAEvnTqFuLIASQLB"
        }
    ]
}
