=== BernhardPosselt/foundryvtt-kotlin/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "skillRequirements",
        "skills",
        "isSecret",
        "isLocked"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skillRequirements": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillRequirement"
          }
        },
        "dc": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "zone",
                "actorLevel"
              ]
            }
          ]
        },
        "skills": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string",
              "enum": [
                "any"
              ]
            }
          ]
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        }
      }
    },
    "SkillRequirement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "skill",
        "proficiency"
      ],
      "properties": {
        "skill": {
          "type": "string"
        },
        "proficiency": {
          "type": "string"
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Tristian.json
{
    "name": "Influence Tristian",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Tristian"
    },
    "success": {
        "message": "You gain 1 Influence Points with Tristian"
    },
    "failure": {
        "message": "You gain no Influence Points with Tristian"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Tristian"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Octavia.json
{
    "name": "Discover Octavia",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Octavia has the lowest DC (skipping any skills that you already know), one of Octavia’s personal biases, one of Octavia’s resistances, or one of Octavia’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Octavia has the lowest DC (skipping any skills that you already know), one of Octavia’s personal biases, one of Octavia’s resistances, or one of Octavia’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Octavia is susceptible to flattery when actually Octavia is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Ekundayo.json
{
    "name": "Discover Ekundayo",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Ekundayo has the lowest DC (skipping any skills that you already know), one of Ekundayo’s personal biases, one of Ekundayo’s resistances, or one of Ekundayo’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Ekundayo has the lowest DC (skipping any skills that you already know), one of Ekundayo’s personal biases, one of Ekundayo’s resistances, or one of Ekundayo’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Ekundayo is susceptible to flattery when actually Ekundayo is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Discover Nok-Nok.json
{
    "name": "Discover Nok-Nok",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.nCwES51tV7FmrfCN",
    "isLocked": true,
    "isSecret": true,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "Choose two of the following: You learn which skill that can Influence Nok-Nok has the lowest DC (skipping any skills that you already know), one of Nok-Nok’s personal biases, one of Nok-Nok’s resistances, or one of Nok-Nok’s weaknesses. you can choose the same option twice to learn two pieces of information from the same category."
    },
    "success": {
        "message": "Choose one of the following: You learn which skill that can Influence Nok-Nok has the lowest DC (skipping any skills that you already know), one of Nok-Nok’s personal biases, one of Nok-Nok’s resistances, or one of Nok-Nok’s weaknesses."
    },
    "failure": {
        "message": "You learn no information."
    },
    "criticalFailure": {
        "message": "Choose a piece of information to learn about, as success, but the information is incorrect. For instance, you might think Nok-Nok is susceptible to flattery when actually Nok-Nok is resistant to flattery."
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Harrim.json
{
    "name": "Influence Harrim",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Harrim"
    },
    "success": {
        "message": "You gain 1 Influence Points with Harrim"
    },
    "failure": {
        "message": "You gain no Influence Points with Harrim"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Harrim"
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/camping-activities/Influence Valerie.json
{
    "name": "Influence Valerie",
    "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.D83mNy8bYqKULEnu",
    "isLocked": true,
    "isSecret": false,
    "skillRequirements": [],
    "skills": "any",
    "criticalSuccess": {
        "message": "You gain 2 Influence Points with Valerie"
    },
    "success": {
        "message": "You gain 1 Influence Points with Valerie"
    },
    "failure": {
        "message": "You gain no Influence Points with Valerie"
    },
    "criticalFailure": {
        "message": "You lose 1 Influence Points with Valerie"
    }
}
