=== BernhardPosselt/foundryvtt-kotlin/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "string"
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "removeAfterRest": {
          "type": "boolean"
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healAfterConsumptionAndRest": {
          "type": "boolean"
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        },
        "damageType": {
          "type": "string",
          "enum": [
            "acid",
            "bludgeoning",
            "cold",
            "electricity",
            "fire",
            "force",
            "mental",
            "piercing",
            "poison",
            "slashing",
            "sonic",
            "spirit",
            "untyped",
            "vitality",
            "void"
          ]
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== BernhardPosselt/foundryvtt-kotlin/data/recipes/Mastodon Steak.json
{
  "name": "Mastodon Steak",
  "icon": "icons/consumables/food/steak-cooked-grilled-brown.webp",
  "basicIngredients": 4,
  "specialIngredients": 3,
  "cookingLoreDC": 34,
  "survivalDC": 36,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.SfNeVcYxBD4uCfrT",
  "level": 14,
  "cost": "225 gp",
  "rarity": "uncommon",
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.0yH2V9UFRyGwXIRn"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Ln9Q3cH6NzGZAJUs"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.M6jcQsHsPEkigTTG",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.xq4qNyrsL5wVYkcQ",
        "removeAfterRest": true
      }
    ]
  }
}

=== BernhardPosselt/foundryvtt-kotlin/data/recipes/Shepherd's Pie.json
{
    "name": "Shepherd's Pie",
    "basicIngredients": 4,
    "specialIngredients": 0,
    "cookingLoreDC": 18,
    "survivalDC": 20,
    "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.GsPVSA1GNm4tvmcR",
    "level": 2,
    "cost": "2 gp",
    "rarity": "uncommon",
    "criticalSuccess": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.3a5uIGu77TLQE9ZB"
            }
        ]
    },
    "criticalFailure": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.84dIJjkOdLeHWkx2"
            }
        ]
    },
    "success": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.COa19ug1vjTGHy04"
            }
        ]
    },
    "favoriteMeal": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.RL8zdU7YyoiduDva"
            }
        ]
    }
}

=== BernhardPosselt/foundryvtt-kotlin/data/recipes/Smoked Trout And Hydra Pate.json
{
    "name": "Smoked Trout And Hydra Pate",
    "basicIngredients": 6,
    "specialIngredients": 2,
    "cookingLoreDC": 26,
    "survivalDC": 28,
    "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.t5pXd39gRgNkPoiu",
    "level": 8,
    "cost": "25 gp",
    "rarity": "uncommon",
    "criticalSuccess": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.4d6roHW75xe52o7A"
            }
        ]
    },
    "criticalFailure": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.LBzsqdKb182lO5Fm",
                "removeAfterRest": true
            }
        ]
    },
    "success": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.miTcZbTcQLJu2NKR",
                "removeAfterRest": true
            }
        ]
    },
    "favoriteMeal": {
        "effects": [
            {
                "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.ve7NrzeHMwLsmbl3"
            }
        ]
    }
}
